# Generated by Django 3.1.4 on 2021-04-09 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_sponsor',
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
