# Generated by Django 3.1.4 on 2021-03-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.TextField(default='admin'),
            preserve_default=False,
        ),
    ]
