# Generated by Django 3.1.3 on 2021-04-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoom',
            name='password',
            field=models.CharField(default='', max_length=120),
        ),
    ]
