# Generated by Django 3.1.4 on 2021-04-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zoom',
            old_name='start_time',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='zoom',
            name='date',
        ),
        migrations.AddField(
            model_name='zoom',
            name='start_date',
            field=models.TextField(default='', max_length=300),
        ),
    ]
