# Generated by Django 3.1.4 on 2021-05-01 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0002_auto_20210428_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoom',
            name='description',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='zoom',
            name='end_date',
            field=models.DateTimeField(max_length=300),
        ),
        migrations.AlterField(
            model_name='zoom',
            name='password',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='zoom',
            name='start_date',
            field=models.DateTimeField(max_length=300),
        ),
        migrations.AlterField(
            model_name='zoom',
            name='zoom_id',
            field=models.TextField(max_length=120),
        ),
    ]
