# Generated by Django 3.1.3 on 2021-04-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0003_auto_20210409_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoom',
            name='zoom_id',
            field=models.TextField(default='', max_length=300),
        ),
    ]
