# Generated by Django 3.1.3 on 2021-04-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0004_zoom_zoom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoom',
            name='start_time',
            field=models.TextField(default='', max_length=300),
        ),
    ]
