# Generated by Django 3.1.4 on 2021-04-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoom', '0005_auto_20210409_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoom',
            name='zoom_id',
            field=models.TextField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='zoom',
            name='zoom_url',
            field=models.URLField(max_length=50),
        ),
    ]
