# Generated by Django 3.1.4 on 2021-02-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default='', max_length=300),
        ),
    ]
